### ISSUE TITLE
Follow cursor/ cursor chomp stops moving if shark and cursor are on the same level up and down. 

### ISSUE THREAD

**Issue by Braga-Rhun** [JJSnader/DesktopAquarium#18]

**Comment by JJSnader** [comment]
This affects all fish in follow cursor mode, not just the shark. Somewhere it's checking if X or Y are within a range from the fish's X,Y coordinates when it should check if both X and Y are within the range.

**Comment by JJSnader** [comment]
This is fixed in v1.13.
