### ISSUE TITLE
Kill Fish feature

### ISSUE THREAD

**Issue by japhethbeiler** [JJSnader/DesktopAquarium#2]
Selecting a fish and clicking "Kill Fish" kills the selected fish and hides the rest. Their names still appear in the fish list, and if you close and reopen the app they reappear swimming around.

Might be something to do with having duplicate ID's.

**Comment by JJSnader** [comment]
Just fixed in previous commit.

**Comment by JJSnader** [comment]
Will be released in v1.1.
